#!/usr/bin/env bash
# Theming: root helpers, GTK, dark mode, the first theme.
# Sourced by install.sh, install_vm.sh and sync.sh through install/lib.sh; defines
# functions and package lists only, and runs nothing.

# x11-theme writes two root-owned files: Chromium's BrowserThemeColor policy and
# ly's colours in /etc/ly/config.ini. As omarchy does for Chromium, each write
# goes through one root-owned helper, with a sudoers rule naming those helpers
# alone, so a theme switch never prompts for a password:
#   /usr/local/lib/cachy-dots/{chromium-theme-color,ly-theme-colors}
#     COPIED from theme/root/ (root must not run a file the user can edit);
#     each accepts only strictly validated colour arguments
#   /etc/sudoers.d/cachy-dots-theme    NOPASSWD for exactly those two paths
THEME_HELPER_DIR=/usr/local/lib/cachy-dots
THEME_HELPERS=(chromium-theme-color ly-theme-colors)
THEME_SUDOERS=/etc/sudoers.d/cachy-dots-theme

setup_theme_helper() {
    local h src rule tmp paths=()
    say "Installing the theme helpers (Chromium, ly)"
    for h in "${THEME_HELPERS[@]}"; do
        src="$REPO/theme/root/$h"
        [ -r "$src" ] || continue
        paths+=("$THEME_HELPER_DIR/$h")
        if [ "$dry" = 1 ]; then
            echo "+ install $src -> $THEME_HELPER_DIR/$h (root:root 755)"
        elif ! cmp -s "$src" "$THEME_HELPER_DIR/$h" 2>/dev/null; then
            $SUDO install -D -o root -g root -m 755 "$src" "$THEME_HELPER_DIR/$h"
            echo "theme helper: $THEME_HELPER_DIR/$h"
        fi
    done
    [ "${#paths[@]}" -gt 0 ] || return 0
    rule="$TARGET_USER ALL=(root) NOPASSWD: $(IFS=,; echo "${paths[*]}" | sed 's/,/, /g')"
    if [ "$dry" = 1 ]; then echo "+ write $THEME_SUDOERS: $rule"; return; fi
    if ! $SUDO grep -qxF "$rule" "$THEME_SUDOERS" 2>/dev/null; then
        tmp=$(mktemp)
        printf '# cachy-dots: lets x11-theme set Chromium'"'"'s colour policy and ly'"'"'s colours.\n%s\n' "$rule" > "$tmp"
        # visudo checks the syntax before anything reaches sudoers.d; a broken
        # file there would lock sudo out entirely.
        if $SUDO visudo -cqf "$tmp"; then
            $SUDO install -o root -g root -m 440 "$tmp" "$THEME_SUDOERS"
            echo "theme helpers: sudoers rule in $THEME_SUDOERS"
        else
            warn "the sudoers rule did not validate; Chromium and ly will not follow the theme"
        fi
        rm -f "$tmp"
    fi
}

# Set a key in an INI file, creating the file and its [Settings] section as
# needed. Used for the GTK settings files, which are plain INI and may already
# exist with the user's own keys.
ini_set() {
    local file="$1" key="$2" value="$3"
    [ "$dry" = 1 ] && { echo "+ set $key=$value in $file"; return; }
    mkdir -p "$(dirname "$file")"
    if [ ! -f "$file" ]; then
        printf '[Settings]\n%s=%s\n' "$key" "$value" > "$file"
        return
    fi
    if grep -qE "^[[:space:]]*${key}[[:space:]]*=" "$file"; then
        sed -i -E "s|^[[:space:]]*${key}[[:space:]]*=.*|${key}=${value}|" "$file"
    elif grep -qE "^\[Settings\]" "$file"; then
        # insert directly after the [Settings] header, not at the end of the
        # file, so a later section cannot claim the key
        awk -v k="$key" -v v="$value" '
            { print }
            /^\[Settings\]/ && !done { print k "=" v; done = 1 }
        ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
    else
        printf '\n[Settings]\n%s=%s\n' "$key" "$value" >> "$file"
    fi
}

# GTK theme and icon theme.
#
# GTK does not read org.gnome.desktop.interface for either of these. It reads the
# XSETTINGS protocol, which a desktop session publishes via a settings daemon.
# There is none here, so the gsettings values that setup_dark_theme() writes are
# ignored by GTK. Confirmed on the VM with Gtk.IconTheme: nm-device-wired
# resolved to /usr/share/icons/hicolor/... however gsettings was set. GTK does
# read ~/.config/gtk-{3,4}.0/settings.ini directly, which fixes it.
#
#   * GTK3 theme: adw-gtk3-dark (adw-gtk-theme), which draws GTK3 like libadwaita
#     and takes the same named colours, so the one gtk.css x11-theme renders
#     recolours GTK3 (Firefox, virt-manager) and GTK4 (nautilus) alike. x11-theme
#     switches it to adw-gtk3 for a light theme. Never "Adwaita-dark": no GTK3
#     theme has that name, and naming one that does not exist makes GTK fall back
#     to *light* Adwaita without a word (menu background #F6F5F4, not #353535).
#   * icon theme: x11-theme, generated by x11-theme from the NetworkManager
#     symbolic icons tinted to the theme (the i3bar tray's nm-applet glyph).
#   * gtk.css: linked from the rendered theme (see install_links).
setup_gtk() {
    local cfg="${XDG_CONFIG_HOME:-$HOME/.config}"
    local dir
    for dir in gtk-3.0 gtk-4.0; do
        [ "$dir" = gtk-3.0 ] && ini_set "$cfg/$dir/settings.ini" gtk-theme-name adw-gtk3-dark
        [ "$dir" = gtk-4.0 ] && ini_set "$cfg/$dir/settings.ini" gtk-theme-name Adwaita
        ini_set "$cfg/$dir/settings.ini" gtk-icon-theme-name x11-theme
        ini_set "$cfg/$dir/settings.ini" gtk-application-prefer-dark-theme 1
    done
    # The previous generated icon theme, before x11-theme took it over.
    [ -d "$HOME/.local/share/icons/pinkrot" ] && run rm -rf "$HOME/.local/share/icons/pinkrot"
    [ "$dry" = 1 ] || echo "gtk: adw-gtk3-dark / Adwaita (dark), icons x11-theme ($cfg/gtk-{3,4}.0/settings.ini)"
}

# Make the session read as dark.
#
# Two halves, and neither is what GTK itself uses - GTK reads XSETTINGS, which
# nothing publishes here. See setup_gtk() for that; this is for everything else:
#   * dconf. color-scheme is what GTK4/libadwaita and Qt consult, and what a
#     desktop would normally republish over XSETTINGS.
#   * the portal. Sandboxed apps and Qt6 (qutebrowser) ask
#     org.freedesktop.portal.Settings instead of reading dconf, and that only
#     works if the backend is running, which needs XDG_CURRENT_DESKTOP to name a
#     desktop the backend is registered for: gtk.portal declares UseIn=gnome.
#     Check it with:
#       busctl --user call org.freedesktop.portal.Desktop \
#         /org/freedesktop/portal/desktop org.freedesktop.portal.Settings \
#         ReadOne ss org.gnome.desktop.interface color-scheme
#
# Best run from inside the desktop session, since both halves need the session
# bus. Run from a bare tty and it explains what to do instead.
setup_dark_theme() {
    command -v gsettings >/dev/null || { warn "gsettings not installed; skipping dark mode"; return; }

    if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
        warn "no session bus: cannot set the system colour scheme from here."
        warn "Run these inside the i3 session to finish:"
        warn "  gsettings set org.gnome.desktop.interface color-scheme prefer-dark"
        warn "  gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark"
        warn "  systemctl --user enable --now xdg-desktop-portal.service xdg-desktop-portal-gtk.service"
        return
    fi

    say "Setting the system colour scheme to dark"
    run gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    run gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark
    # GTK itself ignores this (see setup_gtk), but other consumers read it.
    run gsettings set org.gnome.desktop.interface icon-theme x11-theme

    if command -v systemctl >/dev/null; then
        # The gtk portal backend is gated on XDG_CURRENT_DESKTOP; i3/config sets
        # it for everything i3 spawns, this covers the user services.
        XDG_CURRENT_DESKTOP=GNOME run dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP
        # Both units are static and D-Bus activated, so there is nothing to
        # enable; the first portal request starts them. Starting them here only
        # works with a display: the GTK backend exits at once without one (as
        # over ssh), and systemd then refuses retries until its start limit resets.
        if [ -n "${DISPLAY:-}" ]; then
            run systemctl --user restart xdg-desktop-portal-gtk.service xdg-desktop-portal.service \
                || warn "could not start the xdg-desktop-portal user services"
        else
            echo "portal: no DISPLAY; it starts on demand in the i3 session"
        fi
    fi
}

# Apply a theme, so every file the configs point into the state directory
# exists (i3 includes its colours from there, i3bar runs its rendered config).
# First run: pinkrot, cloned from its repo for the backgrounds and previews; with
# no network, the built-in copy of its colors.toml (theme/themes/pinkrot).
# Later runs pull the installed theme repos (fast-forward only) and re-render
# the current theme, picking up both upstream theme changes and template edits.
PINKROT_REPO=https://github.com/r3b1s/omarchy-pinkrot-theme

setup_theme() {
    local theme="$REPO/bin/x11-theme"
    if [ "$dry" = 1 ]; then echo "+ x11-theme (apply or refresh)"; return; fi
    if [ -f "$HOME/.local/state/omarchy/current/theme.name" ]; then
        say "Updating the installed themes and re-rendering the current one"
        "$theme" update || warn "a theme could not be updated (see above); the current one was still re-rendered"
    else
        say "Applying the default theme (pinkrot)"
        "$theme" install "$PINKROT_REPO" \
            || { warn "could not clone $PINKROT_REPO; using the built-in pinkrot colours"; "$theme" set pinkrot; } \
            || { warn "could not apply any theme"; FAILED=1; }
    fi
}
