# Generated by x11-theme: the [Theme] keys x11-theme writes into
# ~/.config/copyq/copyq.conf (CopyQ keeps its theme there; loading one is a
# GUI-only action). Key names are those of /usr/share/copyq/themes/*.ini.
bg={{ background }}
fg={{ foreground }}
alt_bg={{ dark_background }}
sel_bg={{ accent }}
sel_fg={{ selection_foreground }}
edit_bg={{ lighter_background }}
edit_fg={{ bright_foreground }}
find_bg={{ blue }}
find_fg={{ background }}
num_fg={{ muted }}
notes_bg={{ lighter_background }}
notes_fg={{ foreground }}
show_number=true
show_scrollbars=true
