# Generated by x11-theme; linked as ~/.config/dunst/dunstrc.d/90-theme.conf,
# a drop-in that overrides only the colours of dunst/dunstrc.
[global]
    frame_color = "{{ accent }}"
    highlight = "{{ accent }}"

[urgency_low]
    background = "{{ background }}"
    foreground = "{{ dark_foreground }}"
    frame_color = "{{ muted }}"

[urgency_normal]
    background = "{{ background }}"
    foreground = "{{ foreground }}"
    frame_color = "{{ accent }}"

[urgency_critical]
    background = "{{ mix background red 40% }}"
    foreground = "{{ bright_foreground }}"
    frame_color = "{{ red }}"
