/* Generated by x11-theme; linked as ~/.config/gtk-3.0/gtk.css and
 * ~/.config/gtk-4.0/gtk.css.
 *
 * GTK4/libadwaita (nautilus) and adw-gtk3 (the GTK3 theme set in
 * settings.ini, used by Firefox and virt-manager) both draw from these named
 * colours, so one file recolours both toolkits. Qt follows too: with
 * QT_QPA_PLATFORMTHEME=gtk3 (shell/xprofile) Qt reads its palette from GTK3,
 * through the legacy theme_* names further down. GTK reads this file at start,
 * so running GTK apps pick up a theme change when restarted.
 */
@define-color accent_color {{ blue }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ selection_foreground }};

@define-color destructive_color {{ red }};
@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};
@define-color success_color {{ green }};
@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};
@define-color warning_color {{ orange }};
@define-color warning_bg_color {{ orange }};
@define-color warning_fg_color {{ background }};
@define-color error_color {{ red }};
@define-color error_bg_color {{ red }};
@define-color error_fg_color {{ background }};

@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};
@define-color view_bg_color {{ dark_background }};
@define-color view_fg_color {{ foreground }};
@define-color headerbar_bg_color {{ lighter_background }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ lighter_background }};
@define-color headerbar_backdrop_color {{ background }};
@define-color headerbar_shade_color {{ darker_background }};
@define-color sidebar_bg_color {{ dark_background }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ dark_background }};
@define-color sidebar_shade_color {{ darker_background }};
@define-color secondary_sidebar_bg_color {{ background }};
@define-color secondary_sidebar_fg_color {{ foreground }};
@define-color card_bg_color {{ lighter_background }};
@define-color card_fg_color {{ foreground }};
@define-color card_shade_color {{ darker_background }};
@define-color thumbnail_bg_color {{ lighter_background }};
@define-color thumbnail_fg_color {{ foreground }};
@define-color dialog_bg_color {{ lighter_background }};
@define-color dialog_fg_color {{ foreground }};
@define-color popover_bg_color {{ lighter_background }};
@define-color popover_fg_color {{ foreground }};
@define-color popover_shade_color {{ darker_background }};
@define-color shade_color {{ darker_background }};
@define-color scrollbar_outline_color {{ darker_background }};

/* GTK3 legacy names: older GTK3 widgets, and Qt's gtk3 platform theme. */
@define-color theme_bg_color {{ background }};
@define-color theme_fg_color {{ foreground }};
@define-color theme_base_color {{ dark_background }};
@define-color theme_text_color {{ foreground }};
@define-color theme_selected_bg_color {{ accent }};
@define-color theme_selected_fg_color {{ selection_foreground }};
@define-color insensitive_bg_color {{ background }};
@define-color insensitive_fg_color {{ muted }};
@define-color insensitive_base_color {{ dark_background }};
@define-color theme_unfocused_bg_color {{ background }};
@define-color theme_unfocused_fg_color {{ foreground }};
@define-color theme_unfocused_base_color {{ dark_background }};
@define-color theme_unfocused_text_color {{ foreground }};
@define-color theme_unfocused_selected_bg_color {{ accent }};
@define-color theme_unfocused_selected_fg_color {{ selection_foreground }};
@define-color borders {{ lighter_background }};
@define-color unfocused_borders {{ lighter_background }};
