# Generated by x11-theme from the active theme's colors.toml. i3/config includes
# this before conf.d/, and 01-colors.conf and 15-bar.conf use the variables.
# Do not edit the rendered copy; edit theme/default/themed/i3.conf.tpl.

set $th_bg        {{ background }}
set $th_bg_dark   {{ dark_background }}
set $th_bg_light  {{ lighter_background }}
set $th_fg        {{ foreground }}
set $th_fg_dim    {{ dark_foreground }}
set $th_fg_bright {{ bright_foreground }}
set $th_muted     {{ muted }}
set $th_accent    {{ accent }}
set $th_accent_dim {{ mix background accent 45% }}
set $th_urgent    {{ red }}
set $th_urgent_bg {{ mix background red 40% }}
# i3 paints this on the edge where the next split would open; it is the accent so
# the focused border stays one colour (bright_red left a red bottom edge on kanagawa).
set $th_indicator {{ accent }}
