# Generated by x11-theme. Not read by ly: x11-theme passes these keys to the
# root-owned helper theme/root/ly-theme-colors, which writes them into
# /etc/ly/config.ini (the only file ly reads). Values are 0xAARRGGBB.
bg = 0x00{{ background_strip }}
fg = 0x00{{ foreground_strip }}
border_fg = 0x00{{ accent_strip }}
error_bg = 0x00{{ background_strip }}
error_fg = 0x00{{ bright_red_strip }}
cmatrix_fg = 0x00{{ accent_strip }}
cmatrix_head_col = 0x00{{ bright_red_strip }}
gameoflife_fg = 0x00{{ accent_strip }}
doom_top_color = 0x00{{ accent_strip }}
doom_middle_color = 0x00{{ bright_red_strip }}
doom_bottom_color = 0x00{{ background_strip }}
