/* Generated by x11-theme; rofi/config.rasi @imports this for its colours. */
* {
    bg:     {{ background }};
    bg-row: {{ dark_background }};
    bg-alt: {{ darker_background }};
    fg:     {{ foreground }};
    muted:  {{ muted }};
    accent: {{ accent }};
    on-accent: {{ background }};
    urgent: {{ red }};
}
