# Generated by x11-theme; tmux/tmux.conf source-files this after its own
# settings, and x11-theme re-sources tmux.conf in a running server on a switch.
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg={{ background }},bg={{ foreground }},bold] #S #[bg=default] "
set -g status-right "#[fg={{ foreground }}]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg={{ muted }}]#h | %H:%M:%S | %Y-%m-%d"
set -g window-status-format "#[fg={{ muted }}] #I:#W "
set -g window-status-current-format "#[fg={{ foreground }},bold] #I:#W "
set -g pane-border-style "fg={{ lighter_background }}"
set -g pane-active-border-style "fg={{ accent }}"
set -g message-style "bg=default,fg={{ foreground }}"
set -g message-command-style "bg=default,fg={{ foreground }}"
set -g mode-style "bg={{ selection_background }},fg={{ selection_foreground }}"
setw -g clock-mode-colour "{{ foreground }}"
