# Generated by omarchy-theme-set-templates from the active theme's colors.toml.
# Installed as ~/.config/yazi/flavors/omarchy.yazi/flavor.toml (symlink).
# Do not edit — change this .tpl (or the theme palette).

[mgr]
cwd = { fg = "{{ cyan }}" }

find_keyword  = { fg = "{{ yellow }}", bold = true, italic = true, underline = true }
find_position = { fg = "{{ magenta }}", bg = "reset", bold = true, italic = true }

marker_copied   = { fg = "{{ green }}", bg = "{{ green }}" }
marker_cut      = { fg = "{{ red }}", bg = "{{ red }}" }
marker_marked   = { fg = "{{ cyan }}", bg = "{{ cyan }}" }
marker_selected = { fg = "{{ yellow }}", bg = "{{ yellow }}" }

count_copied   = { fg = "{{ background }}", bg = "{{ green }}" }
count_cut      = { fg = "{{ background }}", bg = "{{ red }}" }
count_selected = { fg = "{{ background }}", bg = "{{ yellow }}" }

border_symbol = "│"
border_style  = { fg = "{{ muted }}" }

[tabs]
active   = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
inactive = { fg = "{{ accent }}", bg = "{{ lighter_background }}" }

[mode]
normal_main = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
normal_alt  = { fg = "{{ accent }}", bg = "{{ lighter_background }}" }
select_main = { fg = "{{ background }}", bg = "{{ cyan }}", bold = true }
select_alt  = { fg = "{{ cyan }}", bg = "{{ lighter_background }}" }
unset_main  = { fg = "{{ background }}", bg = "{{ orange }}", bold = true }
unset_alt   = { fg = "{{ orange }}", bg = "{{ lighter_background }}" }

[status]
perm_sep   = { fg = "{{ muted }}" }
perm_type  = { fg = "{{ blue }}" }
perm_read  = { fg = "{{ yellow }}" }
perm_write = { fg = "{{ red }}" }
perm_exec  = { fg = "{{ green }}" }
progress_label  = { fg = "{{ bright_foreground }}", bold = true }
progress_normal = { fg = "{{ green }}", bg = "{{ selection }}" }
progress_error  = { fg = "{{ yellow }}", bg = "{{ red }}" }

[pick]
border   = { fg = "{{ accent }}" }
active   = { fg = "{{ magenta }}", bold = true }
inactive = {}

[input]
border   = { fg = "{{ accent }}" }
title    = {}
value    = {}
selected = { reversed = true }

[cmp]
border = { fg = "{{ accent }}" }

[tasks]
border  = { fg = "{{ accent }}" }
title   = {}
hovered = { fg = "{{ magenta }}", bold = true }

[which]
mask            = { bg = "{{ lighter_background }}" }
cand            = { fg = "{{ cyan }}" }
rest            = { fg = "{{ dark_foreground }}" }
desc            = { fg = "{{ magenta }}" }
separator       = "  "
separator_style = { fg = "{{ muted }}" }

[help]
on      = { fg = "{{ cyan }}" }
run     = { fg = "{{ magenta }}" }
hovered = { reversed = true, bold = true }
footer  = { fg = "{{ lighter_background }}", bg = "{{ foreground }}" }

[spot]
border   = { fg = "{{ accent }}" }
title    = { fg = "{{ accent }}" }
tbl_col  = { fg = "{{ cyan }}" }
tbl_cell = { fg = "{{ magenta }}", bg = "{{ selection }}" }

[notify]
title_info  = { fg = "{{ green }}" }
title_warn  = { fg = "{{ yellow }}" }
title_error = { fg = "{{ red }}" }

[filetype]
rules = [
	{ mime = "image/*", fg = "{{ cyan }}" },
	{ mime = "{audio,video}/*", fg = "{{ yellow }}" },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "{{ magenta }}" },
	{ mime = "application/{pdf,doc,rtf}", fg = "{{ green }}" },
	{ mime = "vfs/{absent,stale}", fg = "{{ dark_foreground }}" },
	{ url = "*", fg = "{{ foreground }}" },
	{ url = "*/", fg = "{{ accent }}" },
]
